language: python
python:
- '3.6'
install:
- python -m pip install -r requirements.txt
- python -m pip install -e .
script:
- pytest --flake8 --cov=krak
after_success:
- coveralls
deploy:
  provider: pypi
  username: __token__
  password:
    secure: wC1EEYf7zkHFx5akR1cMXUV2fik0/mncK4XoJZjrEpK2L3ht9Z9ZmwTAIGcfAfcdGzhUs0Li/QLE6fIJCj8n8aRZHYpk/jJcgGlZYXOXSrke1w7ficbL7tRuv5oyt74Yyi3Xq5zsdrERz0OCzjDcAEnn2jMyjn2DplDtMnOBEWqmhREAxJLXxrGnmZQ8bgWy6R5u56tnVfySnU8TpgdOtRUm0edXmXXrEzKOwD5kDGr/Lu+aB5lfXBR8EhwGRBG+kacSj/ZrduY2YBTT5TnwJFERDs30wDCdgNJnoL/KuwHOs3AXS+XWFzjx6hMGLOzcH4fX15a+oSorUC7q6KkgsUAnMhNfT3I+eC/Rw9xFbXB9z41cmUeUlprabG64ctI6RBXeMlPxotV0J05z81I9SLMwnlt+DHcVrLecai2gH63+1xZBMNv0AY/NvHrEuHd3js78hXIaAFdCzQi7vJHZIhS/e7hNTXryJ8qzXtkzUEsUxWAD881eG4Q957QbaUxG6jEv4oMRvqmL7ERaozZpU+FZ5IxL0WZrbMTBZ6mg17huD5FkHBHiMPb1cqIWVGvlkz5GuGD/o7Wc+1pTwa1Jnf8i2jpNd3eVsTLl7QzJZsyGFDZHBZtkZSKor8vnB5ZNzuYxUHEdNOafOh+vTLNs+qahrYApQcKTVMbdINKqDt8=
