language: python
python:
- '3.6'
install:
- python -m pip install -r requirements.txt
- python -m pip install -e .
script:
- pytest --flake8 --cov=krak
after_success:
- coveralls
deploy:
  provider: pypi
  user: yetisir
  password:
    secure: X0o4eWmTnD0Y+xJj2afRlmzw451/0d4c7l9oDp/lnZHKRYeDyldKyIycT1odSATpGBJiF3Vkq2CGtX3qr2TFcA90zdat9oNyj7+pnZanAfFKdctpcFCFScisPUNiIyQ5jb36ASGOy/B2WJgFEsO0fP/vKKL25i+U/ICLYMevE2oNQWWMAM5cm5gvOG2OuLGhy3cJ1TxVkpQYHEbC3aUOnkXS9o6jnCkWf4mog8RqMzhGckoUgl9YyAuBvuzG+7ASvykB2E8nDdNsbGbHTwrAvS8Ao0DheL7kCGEA4SZUdBQTp6GinFGYsIS4JZN13MOs88RleKLGpITqrdN3TeQ9F5vTdqWpoMD+HZ7JxqfEJjtyOEiuqbDNjzd05dK5pD3eWeSWIPB+idPr7HsCn8fW9BCTHOzb+uUdbws9C1Y2F3x8F15h5j+GhXsNEKltuo25QsO7LumI0q25NzyrCcoBu+mTxZNjV4MH+Uiu5bHmMNVkZw63w2xvnZAmCmudoXloR/DzxAcPCvQP0ZS0sqY7WivRU9cAiIpaOZ445Selu2ibQ91ZkEhamXkexXMDgkqx7f8h4774R+SrZXHm23V76yqJ7ZqJAqLbOBORP7DICBpG19gD+GSe3Rab7eLFf5KAMcXLCzGudm0Be8VPSHyEDHoVn+dq0Ux+AYGOfO/vqe0=
