version: 2.1

jobs:
  build:
    docker:
      - image: pymesh/pymesh:py3.6-slim
    steps:
      - checkout
      - run: python -m pip install -r requirements.txt
      - run: python -m pip install -e .
      - run: pytest --flake8 --cov=krak 
