version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.06

jobs:
  build:
    docker:
      - image: pymesh/pymesh:py3.6-slim
    steps:
      - checkout
      - run: apt update && apt -y install libstdc++6 python-qt4 libgl1-mesa-glx
      - run: python -m pip install -r requirements.txt
      - run: python -m pip install -e .
      - run: pytest --flake8 --cov=krak
      - run: bash ~/project/.circleci/pypi.sh
      - coveralls/upload
