version: 2.1

jobs:
  build:
    docker:
      - image: pymesh/pymesh:py3.6-slim
    working_directory: ~/krak

    steps:
      - checkout
      - run:
        command: |
          python -m pip install -r requirements.txt
          python -m pip install -e .
      - run:
          command: pytest --flake8 --cov=krak 
