version: '3'

services:
  borehole_database:
    build: ./borehole_database
    ports:
      - 5432:5432
    volumes:
      - borehole_database:/var/lib/borehole_database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: borehole_database
    restart: always

  rest_api:
    build: ./rest_api
    ports:
      - 5001:5001
    volumes:
      - ./rest_api:/app # for debug mode - not neccessary for production
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: borehole_database
      POSTGRES_PORT: 5432
      POSTGRES_HOST: borehole_database
    restart: always
    depends_on:
        - borehole_database

volumes:
  borehole_database:
    driver: local
