swagger: '2.0'
info:
  title: Krak REST api
  version: 0.0.1
consumes:
  - application/json
produces:
  - application/json
basePath: /api

paths:
  /people:
    get:
      operationId: people.read
      tags:
        - people
      summary: test
      description: test
      responses:
        200:
          description: test
          schema:
            type: array
            items:
              properties:
                fname:
                  type: string
                lname:
                  type: string
                timestamp:
                  type: string

