openapi: 3.0.0
info:
  description: Krak REST API
  version: 0.0.1
  title: Krak REST API
paths:
  /borehole:
    get:
      operationId: endpoints.borehole.read_all
      summary: Read all boreholes in db, sorted by id
      description: Read all boreholes in db, sorted by id
      tags:
        - Borehole
      responses:
        "200":
          description: Successfully read boreholes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/borehole_output"
    post:
      operationId: endpoints.borehole.create
      summary: Create a new borehole
      description: Create a new borehole
      tags:
        - Borehole
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/borehole_input"
        description: Borehole to create
        required: true
      responses:
        "201":
          description: Successfully created borehole
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/borehole_output"
  /borehole/{borehole_id}:
    get:
      operationId: endpoints.borehole.read_one
      summary: Read one borehole
      description: Read one borehole
      tags:
        - Borehole
      parameters:
        - name: borehole_id
          in: path
          description: Id of the borehole to get
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successfully read borehole from borehole data operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/borehole_output"
    put:
      operationId: endpoints.borehole.update
      tags:
        - Borehole
      summary: Update a borehole
      description: Update a borehole
      parameters:
        - name: borehole_id
          in: path
          description: Id of the borehole to update
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/borehole_input"
      responses:
        "200":
          description: Successfully updated borehole
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/borehole_output"
    delete:
      operationId: endpoints.borehole.delete
      summary: Delete a borehole
      description: Delete a borehole
      tags:
        - Borehole
      parameters:
        - name: borehole_id
          in: path
          description: Id of the borehole to delete
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successfully deleted borehole
servers:
  - url: /api

components:
  schemas:
    borehole_input:
      type: object
      properties:
        name:
          type: string
          description: Name of the borehole
        x:
          type: number
          description: x position of the collar
        y:
          type: number
          description: Y position of the collar
        z:
          type: number
          description: Z posisiont of the collar
    borehole_output:
      type: object
      properties:
        borehole_id:
          type: integer
          description: Id of the borehole
        name:
          type: string
          description: Name of the borehole
        x:
          type: number
          description: x position of the collar
        y:
          type: number
          description: Y position of the collar
        z:
          type: number
          description: Z posisiont of the collar
